### ISSUE TITLE
Use plugin with ipv6 ...

### ISSUE THREAD

**Issue by Sellto** [emqx/emqx-lwm2m#4]
Hi,

I try to use emqx with the lwm2m server plugin but in the configuration option we can just put the port. 
If i try to set the port to "::1:5683" but service don't start.
I use a lwm2m client with a ipv6 coap address . 

I have modified my conf file as it is described here :
https://github.com/emqx/emqx-tutorial-cn/blob/master/node-name-with-ipv6-address.md

best regards.

Tom

**Comment by qingchuwudi** [comment]
IPv6 is incoming, it will be supported in `4.1.0-alpha.3`.

**Comment by HJianBo** [comment]
@Sellto We have released the v4.1-beta.1 Please try it.

Thanks :)
