### ISSUE TITLE
DTLS + PSK support

### ISSUE THREAD

**Issue by endianjoakim** [emqx/emqx-lwm2m#81]
It seems EMQx in general has DTLS + PSK support for devices. Can this be utilised with the LwM2M plugin?

Also, is there support for reading the PSK secrets from a database?

If not, I would like to request these features.

**Comment by HJianBo** [comment]
Sorry @endianjoakim It does not support lwm2m plugins.

We plan to support it on v4.2.0. Thanks for your feedback :)

**Comment by HJianBo** [comment]
Hi @endianjoakim Thanks for your feedback. We have implemented and released it on v4.2-beta.1

We haven't written the documentation yet, but you can see how to configure it here: https://docs.emqx.io/broker/latest/en/advanced/auth.html#auth-tls-psk
